### ISSUE TITLE
Problem running nodejs version 10.x 

### ISSUE THREAD

**Issue by sutarsha** [ocelotconsulting/node-acme-lambda#29]
We are using this code in our automation for provisioning and renewal of LE certs. This works with lambda runtime 8.10 however this fails with lambda runtime 10.x when deployed. I see no recent commits to the repository also. 

Do we need to have code changes in repo in order for it to work with lambda runtime 10.x?

Awaiting reply.

**Comment by larryboymi** [comment]
I am not aware yet of changes necessary but will test and get back with you. Thanks for submitting the issue!

**Comment by larryboymi** [comment]
With the release of  https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-node-js-12/  I'll skip addressing this issue and combine it with #30
